#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	PATH_TO_FILE="$1"
	IP="$2"
	USERNAME="$3"
	if [ $# -ge 4 ]; then
		PATH_TO_SSH_KEY="$4"
		scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
		exit 0
	fi
	scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
