#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd
# Your script should only display: username, user id & Home directory path for the user
cmd=$(cut -d: -f1,3,6 /etc/passwd)
echo "$cmd"
