#!/usr/bin/env bash
# a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument

# Check if an argument is provided
if [ "$#" -eq 1 ]; then
	# Run the 'whoami' command as the specified user
	sudo -u "$1" whoami
fi
