#!/usr/bin/env bash
# a Bash script that configures the container to meet these requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove

# Change the user in the Nginx configuration
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Ensure Nginx listens on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# grant read/write permission to owner on the nginx config file
chmod 644 /etc/nginx/nginx.conf

# Apache is interfering with nginx, kill its process
pkill apache2

# Start Nginx as nginx (user) with the new configurations
sudo -u nginx service nginx start
